In [ ]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


## Question 1: Array Dimensions

The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

* Number of dimensions in `sales_data`
* Shape of `sales_data`
* Total number of values
* Data type of the array
* Memory occupied by the array

---

In [ ]:
print("Number of dimensions:",sales_data.ndim)
print("shape of array:",sales_data.shape)
print("Total number of values:",sales_data.size)
print("data type:",sales_data.dtype)
print("memory occupied (bytes):",sales_data.nbytes)

Number of dimensions: 2
shape of array: (5, 6)
Total number of values: 30
data type: int64
memory occupied (bytes): 240


## Question 2: Store and Category Count

Calculate the following:

* Total number of stores
* Total number of product categories
* Total number of store-category combinations

---

In [ ]:
print("Total number of stores:",stores.size)
print("Total number of product categories:",categories.size)
print("Total number of store-category combinations:",stores.size * categories.size)

Total number of stores: 5
Total number of product categories: 6
Total number of store-category combinations: 30


## Question 3: Sales Data Type Conversion

The reporting application requires sales values in floating-point format.

Convert `sales_data` into:

* `float32`
* `float64`

Compare the memory used by both arrays.

---

In [ ]:
sales_float32 = sales_data.astype(np.float32)
sales_float64 = sales_data.astype(np.float64)

print("float32 memory:", sales_float32.nbytes, "bytes")
print("float64 memory:", sales_float64.nbytes, "bytes")

float32 memory: 120 bytes
float64 memory: 240 bytes


## Question 4: Bengaluru Store Analysis

The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.

---

In [ ]:
print("Bengaluru sales:")
print(sales_data[0])

Bengaluru sales:
[850000 420000 310000 275000 190000 225000]


## Question 5: Mumbai Cost Analysis

Extract the total cost incurred by the Mumbai store for all product categories.

---

In [ ]:
print("Mumbai cost:")
print(cost_data[3])

Mumbai cost:
[790000 390000 265000 250000 165000 205000]


## Question 6: Electronics Sales Across Stores

The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from `sales_data`.


In [ ]:
print("Electronics sales across stores:")
print(sales_data[:, 0])

Electronics sales across stores:
[ 850000  780000  920000 1050000  690000]


## Question 7: Clothing Cost Across Stores

Extract the Clothing cost for every store from `cost_data`.

In [ ]:
print("Clothing costs across stores:")
print(cost_data[:, 2])

Clothing costs across stores:
[220000 210000 245000 265000 205000]


### Question 8: Hyderabad Furniture Performance

Find the following for Hyderabad:

* Furniture sales
* Furniture cost
* Furniture profit

In [ ]:
sales = sales_data[1, 3]
cost = cost_data[1, 3]
profit = sales - cost

print("Furniture Sales:", sales)
print("Furniture Cost:", cost)
print("Furniture Profit:", profit)

Furniture Sales: 310000
Furniture Cost: 225000
Furniture Profit: 85000


### Question 9: Chennai Category Range

Extract Chennai’s sales for the following categories:

* Groceries
* Clothing
* Furniture

Use array slicing.

In [ ]:
print("Chennai selected category sales:")
print(sales_data[2, 1:4])

Chennai selected category sales:
[390000 340000 260000]


### Question 10: Selected Store Analysis

Extract sales data for:

* Bengaluru
* Chennai
* Pune

Include only:

* Electronics
* Clothing
* Beauty

Use advanced indexing.

In [ ]:
selected = sales_data[[0, 2, 4]][:, [0, 2, 4]]

print("Selected sales data:")
print(selected)

Selected sales data:
[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


## Question 11: Company-Wide Sales

### Calculate the total sales revenue generated by all stores and all categories

In [ ]:
total_sales = sales_data.sum()

print("Total Company Sales:", total_sales)

Total Company Sales: 11675000


## Question 12: Store-Wise Sales

Calculate total sales revenue for each store.

Display the result together with the store names.

In [ ]:
store_sales = sales_data.sum(axis=1)

for store, total in zip(stores, store_sales):
    print(f"{store}: {total}")

Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000
Pune: 1980000


## Question 13: Category-Wise Sales
Calculate total sales for each product category across all stores.

Display each category name with its total sales.

In [ ]:
category_sales = sales_data.sum(axis=0)

for category, total in zip(categories, category_sales):
    print(f"{category}: {total}")

Electronics: 4290000
Groceries: 2185000
Clothing: 1600000
Furniture: 1415000
Beauty: 1010000
Sports: 1175000


## Question 14: Average Sales Per Store

Calculate the average sales generated by each store across all six product categories.

In [ ]:
avg_store_sales = sales_data.mean(axis=1)

for store, avg in zip(stores, avg_store_sales):
    print(f"{store}: {avg:.2f}")

Bengaluru: 378333.33
Hyderabad: 382500.00
Chennai: 385000.00
Mumbai: 470000.00
Pune: 330000.00


### Question 15: Average Sales Per Category

Calculate the average sales of each product category across the five stores.

In [ ]:
avg_category_sales = sales_data.mean(axis=0)

for category, avg in zip(categories, avg_category_sales):
    print(f"{category}: {avg:.2f}")

Electronics: 858000.00
Groceries: 437000.00
Clothing: 320000.00
Furniture: 283000.00
Beauty: 202000.00
Sports: 235000.00


### Question 16: Highest-Selling Store

Identify:

* Index of the store with the highest total sales
* Name of the store
* Total sales generated by that store

In [ ]:
store_totals = sales_data.sum(axis=1)
idx = np.argmax(store_totals)

print("Index:", idx)
print("Store:", stores[idx])
print("Total Sales:", store_totals[idx])

Index: 3
Store: Mumbai
Total Sales: 2820000


## Question 17: Lowest-Selling Store
Identify the store with the lowest overall sales.

In [ ]:
store_totals = sales_data.sum(axis=1)
idx = np.argmin(store_totals)

print("Store:", stores[idx])
print("Total Sales:", store_totals[idx])

Store: Pune
Total Sales: 1980000


## Question 18: Highest-Selling Category

Find the product category that generated the highest total sales across the company.

In [ ]:
category_totals = sales_data.sum(axis=0)
idx = np.argmax(category_totals)

print("Category:", categories[idx])
print("Total Sales:", category_totals[idx])

Category: Electronics
Total Sales: 4290000


### Question 19: Lowest-Selling Category
Find the product category with the lowest total sales across all stores.

In [ ]:
category_totals = sales_data.sum(axis=0)
idx = np.argmin(category_totals)

print("Category:", categories[idx])
print("Total Sales:", category_totals[idx])

Category: Beauty
Total Sales: 1010000


### Question 20: Total Company Cost

Calculate the total cost incurred by SmartMart across all stores and product categories.

In [ ]:
total_cost = cost_data.sum()

print("Total Company Cost:", total_cost)

Total Company Cost: 8600000


### Question 21: Store-Wise Cost

Calculate the total cost incurred by each store.

In [ ]:
store_costs = cost_data.sum(axis=1)

for store, total in zip(stores, store_costs):
    print(f"{store}: {total}")

Bengaluru: 1665000
Hyderabad: 1685000
Chennai: 1710000
Mumbai: 2065000
Pune: 1475000


### Question 22: Category-Wise Cost

Calculate the total cost incurred for each product category across all stores.

In [ ]:
store_costs = cost_data.sum(axis=1)

for store, total in zip(stores, store_costs):
    print(f"{store}: {total}")

Bengaluru: 1665000
Hyderabad: 1685000
Chennai: 1710000
Mumbai: 2065000
Pune: 1475000


### Question 23: Most Expensive Store
Identify the store with the highest total operating cost

In [ ]:
category_costs = cost_data.sum(axis=0)

for category, total in zip(categories, category_costs):
    print(f"{category}: {total}")

Electronics: 3250000
Groceries: 1660000
Clothing: 1145000
Furniture: 1045000
Beauty: 665000
Sports: 835000


### Question 24: Lowest-Cost Store

Identify the store with the lowest total cost.

In [ ]:
store_costs = cost_data.sum(axis=1)
idx = np.argmin(store_costs)

print("Store:", stores[idx])
print("Total Cost:", store_costs[idx])

Store: Pune
Total Cost: 1475000


### Question 25: Most Expensive Product Category

Determine which product category has the highest total cost across all stores.

In [ ]:
category_costs = cost_data.sum(axis=0)
idx = np.argmax(category_costs)

print("Category:", categories[idx])
print("Total Cost:", category_costs[idx])

Category: Electronics
Total Cost: 3250000


### Question 26: Profit Matrix

Calculate the profit generated for every store and product category.

In [ ]:
profit_data = sales_data - cost_data

print("Profit Matrix:")
print(profit_data)

Profit Matrix:
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


### Question 27: Store-Wise Profit

Calculate the total profit generated by each store.

In [ ]:
store_profit = profit_data.sum(axis=1)

for store, profit in zip(stores, store_profit):
    print(f"{store}: {profit}")

Bengaluru: 605000
Hyderabad: 610000
Chennai: 600000
Mumbai: 755000
Pune: 505000


### Question 28: Category-Wise Profit

Calculate the total profit generated by each product category.

In [ ]:
category_profit = profit_data.sum(axis=0)

for category, profit in zip(categories, category_profit):
    print(f"{category}: {profit}")

Electronics: 1040000
Groceries: 525000
Clothing: 455000
Furniture: 370000
Beauty: 345000
Sports: 340000


### Question 29: Most Profitable Store

Identify the store that generated the highest total profit.

In [ ]:
store_sales = sales_data.sum(axis=1)
store_costs = cost_data.sum(axis=1)
store_profit = profit_data.sum(axis=1)

idx = np.argmax(store_profit)

print("Store:", stores[idx])
print("Total Sales:", store_sales[idx])
print("Total Cost:", store_costs[idx])
print("Total Profit:", store_profit[idx])

Store: Mumbai
Total Sales: 2820000
Total Cost: 2065000
Total Profit: 755000


## Question 30: Least Profitable Store

Identify the store that generated the lowest total profit.

In [ ]:
store_profit = profit_data.sum(axis=1)
idx = np.argmin(store_profit)

print("Store:", stores[idx])
print("Total Profit:", store_profit[idx])

Store: Pune
Total Profit: 505000


### Question 31: Most Profitable Category

Find the category with the highest total profit across all stores.

In [ ]:
category_profit = profit_data.sum(axis=0)
idx = np.argmax(category_profit)

print("Category:", categories[idx])
print("Total Profit:", category_profit[idx])

Category: Electronics
Total Profit: 1040000


### Question 32: Least Profitable Category

Find the category with the lowest total profit.

In [ ]:
category_profit = profit_data.sum(axis=0)
idx = np.argmin(category_profit)

print("Category:", categories[idx])
print("Total Profit:", category_profit[idx])

Category: Sports
Total Profit: 340000


### Question 33: Maximum Individual Profit
Find the highest profit generated by any single store-category combination.

In [ ]:
max_profit = profit_data.max()
position = np.unravel_index(np.argmax(profit_data), profit_data.shape)

store_idx, category_idx = position

print("Profit Amount:", max_profit)
print("Store:", stores[store_idx])
print("Category:", categories[category_idx])

Profit Amount: 260000
Store: Mumbai
Category: Electronics


### Question 34: Minimum Individual Profit

Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.

In [ ]:
min_profit = profit_data.min()
position = np.unravel_index(np.argmin(profit_data), profit_data.shape)

store_idx, category_idx = position

print("Profit Amount:", min_profit)
print("Store:", stores[store_idx])
print("Category:", categories[category_idx])

Profit Amount: 55000
Store: Pune
Category: Furniture


### Question 35: Profit Margin Matrix

Calculate the profit margin percentage for every store-category combination.

In [ ]:
profit_margin = (profit_data / sales_data) * 100

print(np.round(profit_margin, 2))

[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


## Question 36: Store-Wise Profit Margin

Calculate the overall profit margin percentage for each store using:

```text
Store Profit Margin =
Total Store Profit / Total Store Sales × 100
```

In [ ]:
store_sales = sales_data.sum(axis=1)
store_profit = profit_data.sum(axis=1)

store_margin = (store_profit / store_sales) * 100

for store, margin in zip(stores, store_margin):
    print(f"{store}: {margin:.2f}%")

Bengaluru: 26.65%
Hyderabad: 26.58%
Chennai: 25.97%
Mumbai: 26.77%
Pune: 25.51%


### Question 37: Category-Wise Profit Margin

Calculate the overall profit margin percentage for each product category.

In [ ]:
category_sales = sales_data.sum(axis=0)
category_profit = profit_data.sum(axis=0)

category_margin = (category_profit / category_sales) * 100

for category, margin in zip(categories, category_margin):
    print(f"{category}: {margin:.2f}%")

Electronics: 24.24%
Groceries: 24.03%
Clothing: 28.44%
Furniture: 26.15%
Beauty: 34.16%
Sports: 28.94%


### Question 38: Best Store by Profit Margin

Identify the store with the highest overall profit margin.

In [ ]:
store_sales = sales_data.sum(axis=1)
store_profit = profit_data.sum(axis=1)

store_margin = (store_profit / store_sales) * 100
idx = np.argmax(store_margin)

print("Best Store:", stores[idx])
print("Profit Margin:", round(store_margin[idx], 2), "%")

Best Store: Mumbai
Profit Margin: 26.77 %


### Question 39: Best Category by Profit Margin

Identify the product category with the highest profit margin.

In [ ]:
category_sales = sales_data.sum(axis=0)
category_profit = profit_data.sum(axis=0)

category_margin = (category_profit / category_sales) * 100
idx = np.argmax(category_margin)

print("Best Category:", categories[idx])
print("Profit Margin:", round(category_margin[idx], 2), "%")

Best Category: Beauty
Profit Margin: 34.16 %


### Question 40: Low-Margin Transactions

Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

* Store
* Category
* Sales
* Cost
* Profit
* Profit margin

Use Boolean indexing.

In [ ]:
profit_data = sales_data - cost_data

profit_margin = (profit_data / sales_data) * 100

low_margin = profit_margin < 22

rows, cols = np.where(low_margin)

for r, c in zip(rows, cols):
    print("Store:", stores[r])
    print("Category:", categories[c])
    print("Sales:", sales_data[r, c])
    print("Cost:", cost_data[r, c])
    print("Profit:", profit_data[r, c])
    print("Profit Margin:", round(profit_margin[r, c], 2), "%")
    print("-" * 30)

profit_data = sales_data - cost_data
profit_margin = (profit_data / sales_data) * 100

low_margin = profit_margin < 22

print(low_margin)
print(np.any(low_margin))

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]
False


### Question 41: High Sales Values

Find all sales values greater than ₹5,00,000.

In [ ]:
high_sales = sales_data[sales_data > 500000]

print("High Sales Values:")
print(high_sales)

High Sales Values:
[ 850000  780000  920000 1050000  510000  690000]


### Question 42: Low Sales Values

Find all sales values below ₹2,00,000.

In [ ]:
low_sales = sales_data[sales_data < 200000]

print("Low Sales Values:")
print(low_sales)

Low Sales Values:
[190000 185000 175000]


### Question 43: High Profit Values

Find all store-category combinations where profit is greater than ₹1,50,000.

In [ ]:
high_profit = profit_data > 150000

rows, cols = np.where(high_profit)

for r, c in zip(rows, cols):
    print("Store:", stores[r])
    print("Category:", categories[c])
    print("Profit:", profit_data[r, c])
    print("-" * 30)

Store: Bengaluru
Category: Electronics
Profit: 210000
------------------------------
Store: Hyderabad
Category: Electronics
Profit: 190000
------------------------------
Store: Chennai
Category: Electronics
Profit: 220000
------------------------------
Store: Mumbai
Category: Electronics
Profit: 260000
------------------------------
Store: Pune
Category: Electronics
Profit: 160000
------------------------------


### Question 44: Moderate Sales Range

Find sales values between ₹2,50,000 and ₹5,00,000.

Use `np.logical_and()`.

In [ ]:
moderate_sales = sales_data[np.logical_and(sales_data >= 250000,
                                           sales_data <= 500000)]

print("Moderate Sales Values:")
print(moderate_sales)

Moderate Sales Values:
[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


### Question 45: Premium Performance

A store-category combination is considered premium when:

* Sales are greater than ₹5,00,000
* Profit is greater than ₹1,50,000

Find all premium-performing combinations.

In [ ]:
premium = (sales_data > 500000) & (profit_data > 150000)

rows, cols = np.where(premium)

for r, c in zip(rows, cols):
    print("Store:", stores[r])
    print("Category:", categories[c])
    print("Sales:", sales_data[r, c])
    print("Profit:", profit_data[r, c])
    print("-" * 30)

Store: Bengaluru
Category: Electronics
Sales: 850000
Profit: 210000
------------------------------
Store: Hyderabad
Category: Electronics
Sales: 780000
Profit: 190000
------------------------------
Store: Chennai
Category: Electronics
Sales: 920000
Profit: 220000
------------------------------
Store: Mumbai
Category: Electronics
Sales: 1050000
Profit: 260000
------------------------------
Store: Pune
Category: Electronics
Sales: 690000
Profit: 160000
------------------------------


### Question 46: Underperforming Combinations

A store-category combination is considered underperforming when:

* Sales are below ₹2,50,000
* Profit margin is below 25%

Find all such combinations.

In [ ]:
underperforming = (sales_data < 250000) & (profit_margin < 25)

rows, cols = np.where(underperforming)

for r, c in zip(rows, cols):
    print("Store:", stores[r])
    print("Category:", categories[c])
    print("Sales:", sales_data[r, c])
    print("Profit Margin:", round(profit_margin[r, c], 2), "%")
    print("-" * 30)

Store: Pune
Category: Furniture
Sales: 225000
Profit Margin: 24.44 %
------------------------------


### Question 47: Category Performance Classification

Create a new array that classifies every sales value as:

* `"High"` when sales are at least ₹5,00,000
* `"Medium"` when sales are between ₹2,50,000 and ₹4,99,999
* `"Low"` when sales are below ₹2,50,000

Use `np.where()` or `np.select()`.

In [ ]:
performance = np.where(
    sales_data >= 500000, "High",
    np.where(sales_data >= 250000, "Medium", "Low")
)

print(performance)

[['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]


## Part 9: Target-Based Analysis

Use the following category-wise monthly sales targets:

```python
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

### Question 48: Target Comparison

Compare every store’s category sales against `sales_targets`.

Use NumPy broadcasting.

In [ ]:
sales_targets = np.array([800000, 450000, 320000,
                          300000, 200000, 230000])

comparison = sales_data - sales_targets

print("Sales - Targets:")
print(comparison)

Sales - Targets:
[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


### Question 49: Target Achievement Matrix

Create a Boolean array where:

* `True` means the store achieved the category target
* `False` means the store failed to achieve the target

In [ ]:
achievement = sales_data >= sales_targets

print("Target Achievement Matrix:")
print(achievement)

Target Achievement Matrix:
[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


### Question 50: Target Achievement Count

Calculate the number of categories in which each store achieved its target.

In [ ]:
target_count = achievement.sum(axis=1)

for store, count in zip(stores, target_count):
    print(f"{store}: {count} targets achieved")

Bengaluru: 1 targets achieved
Hyderabad: 4 targets achieved
Chennai: 2 targets achieved
Mumbai: 6 targets achieved
Pune: 0 targets achieved


### Question 51: Best Target-Performing Store

Find the store that achieved the highest number of category targets.

In [ ]:
target_count = achievement.sum(axis=1)
idx = np.argmax(target_count)

print("Best Target-Performing Store:", stores[idx])
print("Targets Achieved:", target_count[idx])

Best Target-Performing Store: Mumbai
Targets Achieved: 6


### Question 52: Target Achievement by Category

Calculate how many stores achieved the target for each product category.

In [ ]:
category_target_count = achievement.sum(axis=0)

for category, count in zip(categories, category_target_count):
    print(f"{category}: {count} stores achieved target")

Electronics: 3 stores achieved target
Groceries: 2 stores achieved target
Clothing: 2 stores achieved target
Furniture: 2 stores achieved target
Beauty: 2 stores achieved target
Sports: 2 stores achieved target


### Question 53: Sales Target Variance

Calculate the difference between actual sales and target sales for every store.

Use:

```text
Variance = Actual Sales - Target Sales

In [ ]:
variance = sales_data - sales_targets

print("Sales Target Variance:")
print(variance)

Sales Target Variance:
[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


### Question 54: Percentage Above or Below Target

Calculate the percentage variance from the target using:

```text
Percentage Variance =
(Actual Sales - Target Sales) / Target Sales × 100

In [ ]:
percentage_variance = ((sales_data - sales_targets) / sales_targets) * 100

print(np.round(percentage_variance, 2))

[[  6.25  -6.67  -3.12  -8.33  -5.    -2.17]
 [ -2.5    2.22  -7.81   3.33   5.     4.35]
 [ 15.   -13.33   6.25 -13.33  -7.5   -6.52]
 [ 31.25  13.33  17.19  15.    25.    26.09]
 [-13.75 -10.   -12.5  -25.   -12.5  -10.87]]


### Question 55: Stores Missing Electronics Target
Identify stores that failed to achieve the Electronics sales target.

In [ ]:
missing_electronics = sales_data[:, 0] < sales_targets[0]

print("Stores missing Electronics target:")
print(stores[missing_electronics])

Stores missing Electronics target:
['Hyderabad' 'Pune']


### Question 56: Stores Achieving All Targets

Check whether any store achieved its target in all six product categories.

In [ ]:
all_targets = np.all(achievement, axis=1)

print("Stores achieving all targets:")
print(stores[all_targets])

Stores achieving all targets:
['Mumbai']


### Question 57: Stores Achieving At Least One Target

Identify stores that achieved at least one category target.

Use `np.any()`.

In [ ]:
any_target = np.any(achievement, axis=1)

print("Stores achieving at least one target:")
print(stores[any_target])

Stores achieving at least one target:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']


## Part 10: Discount Scenario
SmartMart plans to offer category-wise discounts:

```python
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

### Question 58: Discount Amount Matrix

Calculate the discount amount for each store-category combination.

Use broadcasting.

In [ ]:
discount_rates = np.array([0.10, 0.05, 0.15, 0.12, 0.08, 0.10])

discount_amount = sales_data * discount_rates

print("Discount Amount Matrix:")
print(discount_amount)

Discount Amount Matrix:
[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


### Question 59: Sales After Discount

Calculate the net sales value after applying the category-wise discounts.

In [ ]:
sales_after_discount = sales_data - discount_amount

print("Sales After Discount:")
print(sales_after_discount)

Sales After Discount:
[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


### Question 60: Profit After Discount
Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

In [ ]:
profit_after_discount = sales_after_discount - cost_data

print("Profit After Discount:")
print(profit_after_discount)

Profit After Discount:
[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


### Question 61: Profit Margin After Discount
Calculate the new profit margin after applying discounts.

In [ ]:
new_profit_margin = (profit_after_discount / sales_after_discount) * 100

print(np.round(new_profit_margin, 2))

[[16.34 21.05 16.51 15.29 28.49 20.99]
 [15.95 19.91 16.25 17.52 27.54 21.3 ]
 [15.46 20.38 15.22 14.77 29.49 19.9 ]
 [16.4  19.5  16.86 17.65 28.26 21.46]
 [14.65 19.43 13.87 14.14 28.57 21.41]]


### Question 62: Loss-Making Transactions

Check whether any store-category combination becomes loss-making after discounts.

Display the affected store and category names.

In [ ]:
loss_making = profit_after_discount < 0

rows, cols = np.where(loss_making)

if len(rows) == 0:
    print("No loss-making transactions after discounts.")
else:
    for r, c in zip(rows, cols):
        print("Store:", stores[r])
        print("Category:", categories[c])
        print("Profit After Discount:", profit_after_discount[r, c])
        print("-" * 30)

No loss-making transactions after discounts.


### Question 63: Discount Impact

Calculate how much total revenue the company loses because of the proposed discounts.

In [ ]:
total_discount_loss = discount_amount.sum()

print("Total Revenue Loss:", total_discount_loss)

Total Revenue Loss: 1146350.0


### Question 64: Store Most Affected by Discounts

Identify the store that loses the highest amount of revenue due to discounts.

In [ ]:
store_discount_loss = discount_amount.sum(axis=1)
idx = np.argmax(store_discount_loss)

print("Most Affected Store:", stores[idx])
print("Revenue Loss:", store_discount_loss[idx])

Most Affected Store: Mumbai
Revenue Loss: 277150.0


## Part 11: Tax and Price Adjustment

The government introduces category-wise tax rates:

```python
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

### Question 65: Tax Collection Matrix

Calculate the tax collected on sales for each store and category.

In [ ]:
tax_rates = np.array([0.18, 0.05, 0.12, 0.18, 0.18, 0.12])

tax_collection = sales_data * tax_rates

print("Tax Collection Matrix:")
print(tax_collection)

Tax Collection Matrix:
[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


### Question 66: Sales Including Tax

Calculate the final customer billing value after adding tax.

In [ ]:
sales_with_tax = sales_data + tax_collection

print("Sales Including Tax:")
print(sales_with_tax)

Sales Including Tax:
[[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


### Question 67: Store-Wise Tax Collection

Calculate the total tax collected by each store.

In [ ]:
store_tax = tax_collection.sum(axis=1)

for store, tax in zip(stores, store_tax):
    print(f"{store}: {tax}")

Bengaluru: 321900.0
Hyderabad: 321200.0
Chennai: 331800.0
Mumbai: 401400.0
Pune: 274650.0


### Question 68: Category-Wise Tax Collection

Calculate total tax collected for each category.

In [ ]:
category_tax = tax_collection.sum(axis=0)

for category, tax in zip(categories, category_tax):
    print(f"{category}: {tax}")

Electronics: 772200.0
Groceries: 109250.0
Clothing: 192000.0
Furniture: 254700.0
Beauty: 181800.0
Sports: 141000.0


### Question 69: Highest Tax-Contributing Store

Identify the store that contributes the highest tax amount

In [ ]:
store_tax = tax_collection.sum(axis=1)
idx = np.argmax(store_tax)

print("Highest Tax-Contributing Store:", stores[idx])
print("Tax Amount:", store_tax[idx])

Highest Tax-Contributing Store: Mumbai
Tax Amount: 401400.0


## Part 12: Array Modification

### Question 70: Updated Pune Electronics Sales

The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.

In [ ]:
updated_sales = sales_data.copy()

updated_sales[4, 0] = 740000

print("Original Pune Electronics:", sales_data[4, 0])
print("Updated Pune Electronics:", updated_sales[4, 0])

Original Pune Electronics: 690000
Updated Pune Electronics: 740000


### Question 71: Revised Beauty Cost

Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.

In [ ]:
updated_cost = cost_data.copy()

updated_cost[:, 4] = updated_cost[:, 4] * 0.92

print("Updated Cost Data:")
print(updated_cost)

Updated Cost Data:
[[640000 315000 220000 205000 115000 160000]
 [590000 350000 210000 225000 128800 170000]
 [700000 295000 245000 195000 110400 155000]
 [790000 390000 265000 250000 151800 205000]
 [530000 310000 205000 170000 105800 145000]]


### Question 72: Furniture Cost Increase

Furniture costs increase by 12% for all stores.

Update only the Furniture column.

In [ ]:
furniture_updated = cost_data.copy()

furniture_updated[:, 3] = furniture_updated[:, 3] * 1.12

print("Updated Furniture Costs:")
print(furniture_updated)

Updated Furniture Costs:
[[640000 315000 220000 229600 125000 160000]
 [590000 350000 210000 252000 140000 170000]
 [700000 295000 245000 218400 120000 155000]
 [790000 390000 265000 280000 165000 205000]
 [530000 310000 205000 190400 115000 145000]]


## Question 73: Store Closure Simulation

Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using `np.delete()`.

In [ ]:
sales_without_pune = np.delete(sales_data, 4, axis=0)
cost_without_pune = np.delete(cost_data, 4, axis=0)

print("Sales without Pune:")
print(sales_without_pune)

print("\nCost without Pune:")
print(cost_without_pune)

Sales without Pune:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]

Cost without Pune:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]


### Question 74: Adding a New Store

A new Delhi store is opened with the following data:

```python
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
```

Add Delhi to both arrays using `np.vstack()`.

Also add `"Delhi"` to the stores array.

In [ ]:
delhi_sales = np.array([880000, 475000, 330000, 290000, 215000, 250000])
delhi_cost = np.array([665000, 360000, 235000, 215000, 145000, 180000])

new_sales = np.vstack([sales_data, delhi_sales])
new_cost = np.vstack([cost_data, delhi_cost])

new_stores = np.append(stores, "Delhi")

print("Updated Stores:")
print(new_stores)

print("\nUpdated Sales:")
print(new_sales)

print("\nUpdated Cost:")
print(new_cost)

Updated Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']

Updated Sales:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]

Updated Cost:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]


### Question 75: Adding a New Product Category

SmartMart starts selling Home Appliances.

```python
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
```

Add the new category as a column using `np.column_stack()` or `np.hstack()`.

In [ ]:
home_appliance_sales = np.array([360000, 325000, 390000, 420000, 295000])

home_appliance_cost = np.array([265000, 240000, 285000, 305000, 225000])

sales_extended = np.column_stack([sales_data, home_appliance_sales])
cost_extended = np.column_stack([cost_data, home_appliance_cost])

categories_extended = np.append(categories, "Home Appliances")

print("Updated Categories:")
print(categories_extended)

print("\nExtended Sales Data:")
print(sales_extended)

print("\nExtended Cost Data:")
print(cost_extended)

Updated Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports'
 'Home Appliances']

Extended Sales Data:
[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]

Extended Cost Data:
[[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 165000 205000 305000]
 [530000 310000 205000 170000 115000 145000 225000]]


## Part 13: Sorting and Ranking

### Question 76: Sort Stores by Sales

Sort stores in ascending order based on total sales.

Display store names and sales totals.

In [ ]:
store_totals = sales_data.sum(axis=1)

order = np.argsort(store_totals)

for idx in order:
    print(stores[idx], ":", store_totals[idx])

Pune : 1980000
Bengaluru : 2270000
Hyderabad : 2295000
Chennai : 2310000
Mumbai : 2820000


### Question 77: Rank Stores by Profit

Rank stores from highest to lowest total profit.

Use `np.argsort()`.

In [ ]:
tore_profit = profit_data.sum(axis=1)

rank = np.argsort(store_profit)[::-1]

for idx in rank:
    print(stores[idx], ":", store_profit[idx])

Mumbai : 755000
Hyderabad : 610000
Bengaluru : 605000
Chennai : 600000
Pune : 505000


### Question 78: Sort Categories by Revenue

Sort product categories from highest to lowest total revenue.

In [ ]:
category_sales = sales_data.sum(axis=0)

order = np.argsort(category_sales)[::-1]

for idx in order:
    print(categories[idx], ":", category_sales[idx])

Electronics : 4290000
Groceries : 2185000
Clothing : 1600000
Furniture : 1415000
Sports : 1175000
Beauty : 1010000


### Question 79: Top Three Store-Category Sales

Find the three highest individual sales values in the complete sales matrix.

Display their:

* Sales value
* Store name
* Category name

In [ ]:
flat_indices = np.argsort(sales_data, axis=None)[-3:][::-1]

for idx in flat_indices:
    r, c = np.unravel_index(idx, sales_data.shape)
    print("Sales:", sales_data[r, c])
    print("Store:", stores[r])
    print("Category:", categories[c])
    print("-" * 30)

Sales: 1050000
Store: Mumbai
Category: Electronics
------------------------------
Sales: 920000
Store: Chennai
Category: Electronics
------------------------------
Sales: 850000
Store: Bengaluru
Category: Electronics
------------------------------


### Question 80: Bottom Three Profits

Find the three lowest profit values in the profit matrix.

In [ ]:
flat_indices = np.argsort(profit_data, axis=None)[:3]

for idx in flat_indices:
    r, c = np.unravel_index(idx, profit_data.shape)
    print("Profit:", profit_data[r, c])
    print("Store:", stores[r])
    print("Category:", categories[c])
    print("-" * 30)

Profit: 55000
Store: Pune
Category: Furniture
------------------------------
Profit: 60000
Store: Pune
Category: Sports
------------------------------
Profit: 60000
Store: Chennai
Category: Sports
------------------------------


## Part 14: Statistical Analysis

### Question 81: Sales Statistics

Calculate the following for the complete sales array:

* Minimum
* Maximum
* Mean
* Median
* Standard deviation
* Variance
* 25th percentile
* 50th percentile
* 75th percentile

In [ ]:
print("Minimum:", sales_data.min())
print("Maximum:", sales_data.max())
print("Mean:", sales_data.mean())
print("Median:", np.median(sales_data))
print("Standard Deviation:", np.std(sales_data))
print("Variance:", np.var(sales_data))
print("25th Percentile:", np.percentile(sales_data, 25))
print("50th Percentile:", np.percentile(sales_data, 50))
print("75th Percentile:", np.percentile(sales_data, 75))

Minimum: 175000
Maximum: 1050000
Mean: 389166.6666666667
Median: 302500.0
Standard Deviation: 230322.53954448793
Variance: 53048472222.222206
25th Percentile: 228750.0
50th Percentile: 302500.0
75th Percentile: 416250.0


### Question 82: Store-Wise Standard Deviation

Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.

In [ ]:
store_std = np.std(sales_data, axis=1)

for store, std in zip(stores, store_std):
    print(f"{store}: {std:.2f}")

idx = np.argmax(store_std)

print("\nHighest variation:", stores[idx])

Bengaluru: 223059.53
Hyderabad: 194502.57
Chennai: 249265.59
Mumbai: 271860.87
Pune: 177200.45

Highest variation: Mumbai


### Question 83: Category-Wise Standard Deviation

Determine which product category has the highest variation in sales across stores.

In [ ]:
category_std = np.std(sales_data, axis=0)

for category, std in zip(categories, category_std):
    print(f"{category}: {std:.2f}")

idx = np.argmax(category_std)

print("\nHighest variation category:", categories[idx])

Electronics: 122539.79
Groceries: 43312.82
Clothing: 33911.65
Furniture: 41303.75
Beauty: 26570.66
Sports: 29832.87

Highest variation category: Electronics


### Question 84: Sales Above Company Average

Calculate the company-wide average sales value.

Count how many store-category sales values are above this average

In [ ]:
company_avg = sales_data.mean()

count_above = np.sum(sales_data > company_avg)

print("Company Average:", company_avg)
print("Count Above Average:", count_above)

Company Average: 389166.6666666667
Count Above Average: 10


### Question 85: Outlier Detection

Treat any sales value greater than:

```text
Mean + 1.5 × Standard Deviation
```

as a high-value outlier.

Identify all such sales values.

In [ ]:
mean = sales_data.mean()
std = sales_data.std()

threshold = mean + 1.5 * std

outliers = sales_data[sales_data > threshold]

print("Threshold:", threshold)
print("Outliers:")
print(outliers)

Threshold: 734650.4759833985
Outliers:
[ 850000  780000  920000 1050000]


## Part 15: Reshaping and Transformation

### Question 86: Flatten Sales Data

Convert the two-dimensional sales array into a one-dimensional array using:

* `flatten()`
* `ravel()`

Explain the difference between the two

In [ ]:
flat1 = sales_data.flatten()
flat2 = sales_data.ravel()

print("Flatten:")
print(flat1)

print("\nRavel:")
print(flat2)


Flatten:
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]

Ravel:
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


### Question 87: Reshape Sales Data

Reshape the `5 × 6` sales array into:

* `3 × 10`
* `10 × 3`
* `2 × 15`
* `15 × 2`

Verify that no data is lost.

In [ ]:
shape_3_10 = sales_data.reshape(3, 10)
shape_10_3 = sales_data.reshape(10, 3)
shape_2_15 = sales_data.reshape(2, 15)
shape_15_2 = sales_data.reshape(15, 2)

print("3x10:\n", shape_3_10)
print("\n10x3:\n", shape_10_3)
print("\n2x15:\n", shape_2_15)
print("\n15x2:\n", shape_15_2)

3x10:
 [[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]

10x3:
 [[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]

2x15:
 [[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]

15x2:
 [[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  310000]
 [ 210000  240000]
 [ 920000  390000]
 [ 340000  260000]
 [ 185000  215000]
 [1050000  510000]
 

## Question 88: Transpose Sales Data

Transpose the sales array so that:

* Rows represent product categories
* Columns represent stores

Display the new shape.

In [ ]:
transposed = sales_data.T

print("Transposed Shape:", transposed.shape)
print(transposed)

Transposed Shape: (6, 5)
[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]


### Question 89: Combined Sales and Cost Array

Stack `sales_data` and `cost_data` vertically.

Display the resulting shape.

In [ ]:
combined = np.vstack([sales_data, cost_data])

print("Combined Shape:", combined.shape)
print(combined)

Combined Shape: (10, 6)
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]


### Question 90: Store-Level Combined Data

Create a three-dimensional array where:

* First layer contains sales data
* Second layer contains cost data

Use `np.stack()`.

Display the shape of the new array.


In [ ]:
combined_3d = np.stack([sales_data, cost_data])

print("3D Shape:", combined_3d.shape)
print(combined_3d)

3D Shape: (2, 5, 6)
[[[ 850000  420000  310000  275000  190000  225000]
  [ 780000  460000  295000  310000  210000  240000]
  [ 920000  390000  340000  260000  185000  215000]
  [1050000  510000  375000  345000  250000  290000]
  [ 690000  405000  280000  225000  175000  205000]]

 [[ 640000  315000  220000  205000  125000  160000]
  [ 590000  350000  210000  225000  140000  170000]
  [ 700000  295000  245000  195000  120000  155000]
  [ 790000  390000  265000  250000  165000  205000]
  [ 530000  310000  205000  170000  115000  145000]]]


## Part 16: Missing Data Scenario

The company discovers that some sales values were not recorded.

```python
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])


### Question 91: Missing Value Detection

Find:

* Total number of missing values
* Location of missing values
* Stores and categories containing missing values


In [ ]:
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

missing_mask = np.isnan(sales_with_missing)

print("Total Missing Values:", np.sum(missing_mask))

rows, cols = np.where(missing_mask)

for r, c in zip(rows, cols):
    print("Store:", stores[r], "Category:", categories[c])

Total Missing Values: 4
Store: Bengaluru Category: Clothing
Store: Hyderabad Category: Furniture
Store: Mumbai Category: Groceries
Store: Pune Category: Beauty


### Question 92: Replace Missing Values with Zero

Replace all missing sales values with zero.

In [ ]:
sales_zero = np.nan_to_num(sales_with_missing, nan=0)

print(sales_zero)

[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


### Question 93: Replace with Company Average

Replace missing values with the overall average of available sales values.

Use `np.nanmean()`.

In [ ]:
company_avg = np.nanmean(sales_with_missing)

sales_company_avg = np.where(
    np.isnan(sales_with_missing),
    company_avg,
    sales_with_missing
)

print(sales_company_avg)

[[ 850000.          420000.          398846.15384615  275000.
   190000.          225000.        ]
 [ 780000.          460000.          295000.          398846.15384615
   210000.          240000.        ]
 [ 920000.          390000.          340000.          260000.
   185000.          215000.        ]
 [1050000.          398846.15384615  375000.          345000.
   250000.          290000.        ]
 [ 690000.          405000.          280000.          225000.
   398846.15384615  205000.        ]]


### Question 94: Replace with Category Average

Replace each missing value with the average sales value of its respective product category.

In [ ]:
category_avg = np.nanmean(sales_with_missing, axis=0)

sales_category_avg = sales_with_missing.copy()

rows, cols = np.where(np.isnan(sales_category_avg))

for r, c in zip(rows, cols):
    sales_category_avg[r, c] = category_avg[c]

print(sales_category_avg)

[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]


### Question 95: Missing Value Impact

Compare total sales before and after replacing missing values with zero.

In [ ]:
original_total = np.nansum(sales_with_missing)
zero_total = sales_zero.sum()

print("Original Total:", original_total)
print("After Replacing with Zero:", zero_total)
print("Difference:", original_total - zero_total)

Original Total: 10370000.0
After Replacing with Zero: 10370000.0
Difference: 0.0


## Part 17: Conditional Business Decisions

### Question 96: Store Performance Labels

Classify each store based on total sales:

* `"Excellent"`: Total sales above ₹28,00,000
* `"Good"`: Total sales between ₹24,00,000 and ₹28,00,000
* `"Needs Improvement"`: Total sales below ₹24,00,000

Use `np.select()`.

In [ ]:
store_totals = sales_data.sum(axis=1)

conditions = [
    store_totals > 2800000,
    (store_totals >= 2400000) & (store_totals <= 2800000),
    store_totals < 2400000
]

choices = ["Excellent", "Good", "Needs Improvement"]

labels = np.select(conditions, choices, default="Unknown")

for store, total, label in zip(stores, store_totals, labels):
    print(f"{store}: {total} -> {label}")

Bengaluru: 2270000 -> Needs Improvement
Hyderabad: 2295000 -> Needs Improvement
Chennai: 2310000 -> Needs Improvement
Mumbai: 2820000 -> Excellent
Pune: 1980000 -> Needs Improvement


### Question 97: Profitability Classification

Classify each store-category combination as:

* `"Highly Profitable"`: Profit above ₹2,00,000
* `"Profitable"`: Profit between ₹1,00,000 and ₹2,00,000
* `"Low Profit"`: Profit below ₹1,00,000
* `"Loss"`: Profit below zero


In [ ]:
profit_class = np.select(
    [
        profit_data > 200000,
        (profit_data >= 100000) & (profit_data <= 200000),
        (profit_data >= 0) & (profit_data < 100000),
        profit_data < 0
    ],
    [
        "Highly Profitable",
        "Profitable",
        "Low Profit",
        "Loss"
    ],
    default="Low Profit"
)

print(profit_class)

[['Highly Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Profitable' 'Profitable' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']]


### Question 98: Expansion Recommendation
A store is eligible for expansion when:

* Total sales are above ₹25,00,000
* Total profit is above ₹7,00,000
* Overall profit margin is above 25%

Identify eligible stores.

In [ ]:
store_sales = sales_data.sum(axis=1)
store_costs = cost_data.sum(axis=1)
store_profit = profit_data.sum(axis=1)
store_margin = (store_profit / store_sales) * 100

eligible = (
    (store_sales > 2500000) &
    (store_profit > 700000) &
    (store_margin > 25)
)

print("Eligible Stores:")
print(stores[eligible])

Eligible Stores:
['Mumbai']


### Question 99: Category Promotion Recommendation

A product category should receive additional promotion when:

* Average sales are below ₹3,00,000
* Profit margin is above 25%

Identify the categories that satisfy these conditions.

In [ ]:
category_sales = sales_data.mean(axis=0)
category_profit = profit_data.sum(axis=0)
category_total_sales = sales_data.sum(axis=0)

category_margin = (category_profit / category_total_sales) * 100

promotion = (
    (category_sales < 300000) &
    (category_margin > 25)
)

print("Categories for Promotion:")
print(categories[promotion])

Categories for Promotion:
['Furniture' 'Beauty' 'Sports']


### Question 100: Cost Optimization Recommendation

Find store-category combinations where:

* Cost is greater than ₹2,50,000
* Profit margin is below 25%

These combinations should be reviewed for cost optimization.

In [ ]:
optimization = (cost_data > 250000) & (profit_margin < 25)

rows, cols = np.where(optimization)

for r, c in zip(rows, cols):
    print("Store:", stores[r])
    print("Category:", categories[c])
    print("Cost:", cost_data[r, c])
    print("Profit Margin:", round(profit_margin[r, c], 2), "%")
    print("-" * 30)

Store: Bengaluru
Category: Electronics
Cost: 640000
Profit Margin: 24.71 %
------------------------------
Store: Hyderabad
Category: Electronics
Cost: 590000
Profit Margin: 24.36 %
------------------------------
Store: Hyderabad
Category: Groceries
Cost: 350000
Profit Margin: 23.91 %
------------------------------
Store: Chennai
Category: Electronics
Cost: 700000
Profit Margin: 23.91 %
------------------------------
Store: Chennai
Category: Groceries
Cost: 295000
Profit Margin: 24.36 %
------------------------------
Store: Mumbai
Category: Electronics
Cost: 790000
Profit Margin: 24.76 %
------------------------------
Store: Mumbai
Category: Groceries
Cost: 390000
Profit Margin: 23.53 %
------------------------------
Store: Pune
Category: Electronics
Cost: 530000
Profit Margin: 23.19 %
------------------------------
Store: Pune
Category: Groceries
Cost: 310000
Profit Margin: 23.46 %
------------------------------


# Part 18: Inventory Scenario

Use the following inventory arrays:


In [ ]:
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])


### Question 101: Closing Stock

Calculate closing stock using:

```text
Closing Stock = Opening Stock - Units Sold

In [ ]:
import numpy as np

# Closing Stock = Opening Stock - Units Sold
closing_stock = opening_stock - units_sold

print("Closing Stock:")
print(closing_stock)

Closing Stock:
[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


### Question 102: Low-Stock Identification

Identify store-category combinations where closing stock is below 30 units.

In [ ]:
low_stock = closing_stock < 30

rows, cols = np.where(low_stock)

for r, c in zip(rows, cols):
    print("Store:", stores[r])
    print("Category:", categories[c])
    print("Closing Stock:", closing_stock[r, c])
    print("-" * 30)

Store: Bengaluru
Category: Electronics
Closing Stock: 25
------------------------------
Store: Bengaluru
Category: Furniture
Closing Stock: 25
------------------------------
Store: Hyderabad
Category: Electronics
Closing Stock: 25
------------------------------
Store: Hyderabad
Category: Furniture
Closing Stock: 25
------------------------------
Store: Chennai
Category: Electronics
Closing Stock: 25
------------------------------
Store: Chennai
Category: Furniture
Closing Stock: 25
------------------------------
Store: Mumbai
Category: Electronics
Closing Stock: 25
------------------------------
Store: Pune
Category: Electronics
Closing Stock: 25
------------------------------
Store: Pune
Category: Furniture
Closing Stock: 20
------------------------------


### Question 103: Stock Availability Percentage

Calculate the percentage of opening stock that remains unsold.

In [ ]:
stock_remaining_pct = (closing_stock / opening_stock) * 100

print(np.round(stock_remaining_pct, 2))

[[20.83 15.56 20.   27.78 24.   22.22]
 [22.73 16.   17.86 25.   22.22 22.5 ]
 [19.23 16.67 15.62 29.41 25.   23.53]
 [16.67 14.55 15.71 25.   21.67 20.45]
 [25.   17.5  21.15 26.67 25.   25.  ]]


### Question 104: Fast-Moving Products

A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.

In [ ]:
sold_pct = (units_sold / opening_stock) * 100

fast_moving = sold_pct > 80

rows, cols = np.where(fast_moving)

for r, c in zip(rows, cols):
    print("Store:", stores[r])
    print("Category:", categories[c])
    print("Sold %:", round(sold_pct[r, c], 2))
    print("-" * 30)

Store: Bengaluru
Category: Groceries
Sold %: 84.44
------------------------------
Store: Hyderabad
Category: Groceries
Sold %: 84.0
------------------------------
Store: Hyderabad
Category: Clothing
Sold %: 82.14
------------------------------
Store: Chennai
Category: Electronics
Sold %: 80.77
------------------------------
Store: Chennai
Category: Groceries
Sold %: 83.33
------------------------------
Store: Chennai
Category: Clothing
Sold %: 84.38
------------------------------
Store: Mumbai
Category: Electronics
Sold %: 83.33
------------------------------
Store: Mumbai
Category: Groceries
Sold %: 85.45
------------------------------
Store: Mumbai
Category: Clothing
Sold %: 84.29
------------------------------
Store: Pune
Category: Groceries
Sold %: 82.5
------------------------------


### Question 105: Category-Wise Units Sold

Calculate the total units sold for each product category.

In [ ]:
category_units = units_sold.sum(axis=0)

for category, total in zip(categories, category_units):
    print(f"{category}: {total}")

Electronics: 485
Groceries: 1950
Clothing: 1240
Furniture: 345
Beauty: 980
Sports: 720


### Question 106: Store-Wise Units Sold

Calculate total units sold by each store.

In [ ]:
store_units = units_sold.sum(axis=1)

for store, total in zip(stores, store_units):
    print(f"{store}: {total}")

Bengaluru: 1110
Hyderabad: 1175
Chennai: 1095
Mumbai: 1390
Pune: 950


### Question 107: Best Store by Unit Sales

Identify the store that sold the highest total number of units.

In [ ]:
store_units = units_sold.sum(axis=1)

idx = np.argmax(store_units)

print("Best Store:", stores[idx])
print("Units Sold:", store_units[idx])

Best Store: Mumbai
Units Sold: 1390


### Question 108: Reorder Requirement

A store should reorder a category when closing stock is below 25 units.

Create a Boolean reorder matrix.


In [ ]:
reorder_matrix = closing_stock < 25

print(reorder_matrix)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


## Question 109: Reorder Quantity

Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.

In [ ]:
reorder_qty = np.where(closing_stock < 25,
                       100 - closing_stock,
                       0)

print(reorder_qty)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


## Part 19: Advanced NumPy Questions

### Question 110: Cumulative Store Sales

Calculate cumulative category sales for each store using `np.cumsum()

In [ ]:
cumulative_store_sales = np.cumsum(sales_data, axis=1)

print(cumulative_store_sales)

[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


### Question 111: Cumulative Company Sales

Flatten the sales array and calculate cumulative company sales.

In [ ]:
flat_sales = sales_data.flatten()

cumulative_company_sales = np.cumsum(flat_sales)

print(cumulative_company_sales)

[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


### Question 112: Sales Difference Between Categories

Calculate the difference between consecutive category sales for each store using `np.diff()`.

In [ ]:
sales_difference = np.diff(sales_data, axis=1)

print(sales_difference)

[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


### Question 113: Unique Sales Values

Find all unique sales values in `sales_data`.

Also count the frequency of each value.

In [ ]:
unique_values, frequency = np.unique(sales_data, return_counts=True)

for value, count in zip(unique_values, frequency):
    print(f"{value}: {count}")

175000: 1
185000: 1
190000: 1
205000: 1
210000: 1
215000: 1
225000: 2
240000: 1
250000: 1
260000: 1
275000: 1
280000: 1
290000: 1
295000: 1
310000: 2
340000: 1
345000: 1
375000: 1
390000: 1
405000: 1
420000: 1
460000: 1
510000: 1
690000: 1
780000: 1
850000: 1
920000: 1
1050000: 1


### Question 114: Search for Specific Sales

Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

In [ ]:
exists = np.any(sales_data == 420000)

print("420000 Exists:", exists)

rows, cols = np.where(sales_data == 420000)

for r, c in zip(rows, cols):
    print("Store:", stores[r])
    print("Category:", categories[c])

420000 Exists: True
Store: Bengaluru
Category: Groceries


### Question 115: Compare Sales and Cost

Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using `np.all()`

In [ ]:
comparison = sales_data > cost_data

print(comparison)

print("All combinations profitable:", np.all(comparison))

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
All combinations profitable: True


## Question 116: Clip Profit Values

For reporting purposes, management wants profit values limited to:

* Minimum: ₹75,000
* Maximum: ₹2,50,000

Use `np.clip()` to create a reporting profit array.

In [ ]:
reporting_profit = np.clip(profit_data, 75000, 250000)

print(reporting_profit)

[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


### Question 117: Normalize Sales Data

Normalize all sales values using min-max normalization:

```text
Normalized Sales =
(Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)

In [ ]:
min_sales = sales_data.min()
max_sales = sales_data.max()

normalized_sales = (sales_data - min_sales) / (max_sales - min_sales)

print(np.round(normalized_sales, 4))

[[0.7714 0.28   0.1543 0.1143 0.0171 0.0571]
 [0.6914 0.3257 0.1371 0.1543 0.04   0.0743]
 [0.8514 0.2457 0.1886 0.0971 0.0114 0.0457]
 [1.     0.3829 0.2286 0.1943 0.0857 0.1314]
 [0.5886 0.2629 0.12   0.0571 0.     0.0343]]


### Question 118: Standardize Sales Data

Standardize sales using:

```text
Standardized Sales =
(Sales - Mean Sales) / Standard Deviation

In [ ]:
mean_sales = sales_data.mean()
std_sales = sales_data.std()

standardized_sales = (sales_data - mean_sales) / std_sales

print(np.round(standardized_sales, 4))

[[ 2.0008  0.1339 -0.3437 -0.4957 -0.8647 -0.7128]
 [ 1.6969  0.3075 -0.4088 -0.3437 -0.7779 -0.6476]
 [ 2.3047  0.0036 -0.2135 -0.5608 -0.8864 -0.7562]
 [ 2.8692  0.5246 -0.0615 -0.1918 -0.6042 -0.4306]
 [ 1.3061  0.0687 -0.474  -0.7128 -0.9299 -0.7996]]


### Question 119: Round Values

Convert profit margin values into:

* Two decimal places
* Nearest whole number
* Floor values
* Ceiling values

In [ ]:
print("Two Decimal Places:")
print(np.round(profit_margin, 2))

print("\nNearest Whole Number:")
print(np.round(profit_margin))

print("\nFloor Values:")
print(np.floor(profit_margin))

print("\nCeiling Values:")
print(np.ceil(profit_margin))

Two Decimal Places:
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]

Nearest Whole Number:
[[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]

Floor Values:
[[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]

Ceiling Values:
[[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]


### Question 120: Save and Load Data

Save the following arrays as NumPy binary files:

* `sales_data.npy`
* `cost_data.npy`
* `profit_data.npy`

Load them back and verify that the loaded arrays are equal to the original arrays.

In [ ]:
np.save("sales_data.npy", sales_data)
np.save("cost_data.npy", cost_data)
np.save("profit_data.npy", profit_data)

# Load arrays

sales_loaded = np.load("sales_data.npy")
cost_loaded = np.load("cost_data.npy")
profit_loaded = np.load("profit_data.npy")

# Verify equality

print("Sales Equal:", np.array_equal(sales_data, sales_loaded))
print("Cost Equal:", np.array_equal(cost_data, cost_loaded))
print("Profit Equal:", np.array_equal(profit_data, profit_loaded))

Sales Equal: True
Cost Equal: True
Profit Equal: True
